/*
 *  Main Screen is the main menu for accessing the entire program
 */
package database;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import jxl.Workbook;
import jxl.write.*;


public class MainScreen extends javax.swing.JFrame {

    //variables accessed by multiple functions (button presses) below
    private Statement stmt;
    private Connection c;
    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        //initialize GUI via Netbeans default code
        initComponents();
        try {
            //initialize variables for SQL
            c = DriverManager.getConnection("jdbc:sqlite:bank.db");
            c.setAutoCommit(false);
            stmt = c.createStatement();
            /*//create tables in the database -- uncomment for creating a new database
            String sql = "";
            sql =   "CREATE TABLE CUSTOMER(" +
                    "SSN		CHAR(9)		PRIMARY KEY," +
                    "Full_name		VARCHAR(80)     NOT NULL," +
                    "Birthdate		DATE		NOT NULL," +
                    "Sex		CHAR(1));";
            stmt.executeUpdate(sql);
            sql =   "CREATE TABLE EMPLOYEE(" +
                    "SSN		CHAR(9)		PRIMARY KEY," +
                    "Full_name		VARCHAR(80)     NOT NULL," +
                    "Birthdate		DATE		NOT NULL," +
                    "Sex		CHAR(1)," +
                    "Position		VARCHAR(20)," +
                    "Hourly_wage	DECIMAL(5,2)	NOT NULL);";
            stmt.executeUpdate(sql);
            sql =   "CREATE TABLE ACCOUNT(" +
                    "ID			INT		PRIMARY KEY," +
                    "Balance		DOUBLE(16,2)	NOT NULL," +
                    "Interest_rate	DOUBLE(6,5));";
            stmt.executeUpdate(sql);
            sql =   "CREATE TABLE ACCOUNT_AUTHORIZATION(" +
                    "ID			INT," +
                    "CSSN		CHAR(9)," +
                    "PRIMARY KEY(ID, CSSN)," +
                    "FOREIGN KEY (ID) REFERENCES ACCOUNT(ID)," +
                    "FOREIGN KEY (CSSN) REFERENCES CUSTOMER(SSN));";
            stmt.executeUpdate(sql);
            sql =   "CREATE TABLE TRANS_ACTION(" +
                    "Timestamp		DATETIME," +
                    "CSSN		CHAR(9)," +
                    "Account_ID         INT		NOT NULL," +
                    "Type		VARCHAR(10)	NOT NULL," +
                    "Amount		DOUBLE(16,2)	NOT NULL," +
                    "ESSN		CHAR(9)		NOT NULL," +
                    "PRIMARY KEY(Timestamp, CSSN)," +
                    "FOREIGN KEY (CSSN) REFERENCES CUSTOMER(SSN)," +
                    "FOREIGN KEY (Account_ID) REFERENCES ACCOUNT(ID)," +
                    "FOREIGN KEY (ESSN) REFERENCES EMPLOYEE(SSN));";
            stmt.executeUpdate(sql);*/
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERROR: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jButton1.setText("View Employees");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("View Customers");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Add Employee");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Add Customer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Request Transaction");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Main Screen");

        jButton6.setText("Open New Account");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Print Statement");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addComponent(jButton5)
                    .addComponent(jButton7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // View Employee buttom pressed
        new ViewPerson(true, stmt).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // View Customer button pressed
        new ViewPerson(false, stmt).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Add Employee button pressed
        new NewPerson(true, stmt).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Add Customer button pressed
        new NewPerson(false, stmt).setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // Open New Account button pressed
        new NewAccount(stmt).setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Request Transaction button pressed
        new Transaction(stmt).setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        //when the window closes, commit changes to the database file and close objects
        try {
            stmt.close();
            c.commit();
            c.close();
        } catch (SQLException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // Print Statement button pressed
        try
        {
            WritableWorkbook wBook; //this is the Excel file
            WritableSheet masterSheet; //this is a sheet in the Excel file
            //declare font and font size (Times New Roman, size 12)
            WritableCellFormat cellFormat = new WritableCellFormat(new WritableFont(WritableFont.TIMES,12));
            //turn word wrap on if needed
            cellFormat.setWrap(true);
            //create an Excel file at the designated file location on the computer
            wBook = Workbook.createWorkbook(new File("statement.xls"));
            //initialize sheet name
            masterSheet = wBook.createSheet("Statement",0);
            //get account number from user
            String id = JOptionPane.showInputDialog("Enter Account ID #");
            
            //set column widths in Excel file
            masterSheet.setColumnView(0,21,cellFormat);
            masterSheet.setColumnView(1,20,cellFormat);
            masterSheet.setColumnView(2,12,cellFormat);
            masterSheet.setColumnView(3,12,cellFormat);
            masterSheet.setColumnView(4,20,cellFormat);
            //give header names
            masterSheet.addCell(new Label(0,0,"Timestamp",cellFormat));
            masterSheet.addCell(new Label(1,0,"Customer Name",cellFormat));
            masterSheet.addCell(new Label(2,0,"Type",cellFormat));
            masterSheet.addCell(new Label(3,0,"Amount",cellFormat));
            masterSheet.addCell(new Label(4,0,"Employee Name",cellFormat));
            //get transaction details
            ResultSet rs = stmt.executeQuery("SELECT T.Timestamp, C.Full_name, Account_ID, T.Type, T.Amount, E.Full_name " + 
                                             "FROM TRANS_ACTION AS T INNER JOIN EMPLOYEE AS E INNER JOIN CUSTOMER AS C " +
                                             "WHERE T.Account_ID=" + id + " AND C.SSN=T.CSSN AND E.SSN=T.ESSN;");
            //populate Excel file from the query
            for(int row = 1; rs.next(); row++)
            {
                //fill columns in this row
                for(int col = 1; col<=2; col++)
                    masterSheet.addCell(new Label(col-1,row,rs.getString(col),cellFormat));
                for(int col = 4; col<=6; col++)
                    masterSheet.addCell(new Label(col-2,row,rs.getString(col),cellFormat));
            }
            //flush output and close
            wBook.write();
            wBook.close();
            //open Excel file with default program
            Desktop.getDesktop().open(new File("statement.xls"));
        }
        //catch the various exceptions that may be thrown
        catch(IOException e) {
            JOptionPane.showMessageDialog(null, "ERROR: new file failed -- " + e.getMessage());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERROR: query failed -- " + e.getMessage());
        } catch (WriteException e) {
            JOptionPane.showMessageDialog(null, "ERROR: write failed -- " + e.getMessage());
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
